name: ODD Collector GCP release

on:
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_TOKEN_GHCR }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  commit_version:
    name: 'Commit project version to github'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: 1.3.2
          virtualenvs-create: false

      - name: Patch package version
        run: |
          poetry version patch
          echo "VERSION = \"$(poetry version -s)\"" > odd_collector_gcp/__version__.py


      - name: Update repository with up-to-date and version
        run: |
          git config --global user.email "opendatadiscovery-bot@provectus.com"
          git config --global user.name "OpenDataDiscovery Bot"
          if [ -n "$(git status --porcelain)" ]
          then
            git add .
            git commit -m "Bump package version"
            git push origin main
          fi
